/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class AConditionalExpr extends PExpr
{
    private PExpr _cond_;
    private PExpr _then_;
    private PExpr _else_;

    public AConditionalExpr()
    {
        // Constructor
    }

    public AConditionalExpr(
        @SuppressWarnings("hiding") PExpr _cond_,
        @SuppressWarnings("hiding") PExpr _then_,
        @SuppressWarnings("hiding") PExpr _else_)
    {
        // Constructor
        setCond(_cond_);

        setThen(_then_);

        setElse(_else_);

    }

    @Override
    public Object clone()
    {
        return new AConditionalExpr(
            cloneNode(this._cond_),
            cloneNode(this._then_),
            cloneNode(this._else_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConditionalExpr(this);
    }

    public PExpr getCond()
    {
        return this._cond_;
    }

    public void setCond(PExpr node)
    {
        if(this._cond_ != null)
        {
            this._cond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond_ = node;
    }

    public PExpr getThen()
    {
        return this._then_;
    }

    public void setThen(PExpr node)
    {
        if(this._then_ != null)
        {
            this._then_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._then_ = node;
    }

    public PExpr getElse()
    {
        return this._else_;
    }

    public void setElse(PExpr node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond_)
            + toString(this._then_)
            + toString(this._else_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond_ == child)
        {
            this._cond_ = null;
            return;
        }

        if(this._then_ == child)
        {
            this._then_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond_ == oldChild)
        {
            setCond((PExpr) newChild);
            return;
        }

        if(this._then_ == oldChild)
        {
            setThen((PExpr) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
