/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import java.util.*;
import plume.analysis.*;

@SuppressWarnings("nls")
public final class AMethodCallExpr extends PExpr
{
    private PExpr _target_;
    private TId _id_;
    private final LinkedList<PExpr> _expr_ = new LinkedList<PExpr>();

    public AMethodCallExpr()
    {
        // Constructor
    }

    public AMethodCallExpr(
        @SuppressWarnings("hiding") PExpr _target_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<PExpr> _expr_)
    {
        // Constructor
        setTarget(_target_);

        setId(_id_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AMethodCallExpr(
            cloneNode(this._target_),
            cloneNode(this._id_),
            cloneList(this._expr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMethodCallExpr(this);
    }

    public PExpr getTarget()
    {
        return this._target_;
    }

    public void setTarget(PExpr node)
    {
        if(this._target_ != null)
        {
            this._target_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._target_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PExpr> getExpr()
    {
        return this._expr_;
    }

    public void setExpr(List<PExpr> list)
    {
        this._expr_.clear();
        this._expr_.addAll(list);
        for(PExpr e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._target_)
            + toString(this._id_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._target_ == child)
        {
            this._target_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._expr_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._target_ == oldChild)
        {
            setTarget((PExpr) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PExpr> i = this._expr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
