/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class ASuperExpr extends PExpr
{
    private TKsuper _ksuper_;

    public ASuperExpr()
    {
        // Constructor
    }

    public ASuperExpr(
        @SuppressWarnings("hiding") TKsuper _ksuper_)
    {
        // Constructor
        setKsuper(_ksuper_);

    }

    @Override
    public Object clone()
    {
        return new ASuperExpr(
            cloneNode(this._ksuper_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuperExpr(this);
    }

    public TKsuper getKsuper()
    {
        return this._ksuper_;
    }

    public void setKsuper(TKsuper node)
    {
        if(this._ksuper_ != null)
        {
            this._ksuper_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ksuper_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ksuper_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ksuper_ == child)
        {
            this._ksuper_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ksuper_ == oldChild)
        {
            setKsuper((TKsuper) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
