/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class TB extends Token
{
    public TB()
    {
        super.setText(">");
    }

    public TB(int line, int pos)
    {
        super.setText(">");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TB(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTB(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TB text.");
    }
}
