/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class TKas extends Token
{
    public TKas()
    {
        super.setText("as");
    }

    public TKas(int line, int pos)
    {
        super.setText("as");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKas(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKas(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKas text.");
    }
}
