/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class TKerror extends Token
{
    public TKerror()
    {
        super.setText("error");
    }

    public TKerror(int line, int pos)
    {
        super.setText("error");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKerror(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKerror(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKerror text.");
    }
}
