/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class TKextends extends Token
{
    public TKextends()
    {
        super.setText("extends");
    }

    public TKextends(int line, int pos)
    {
        super.setText("extends");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKextends(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKextends(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKextends text.");
    }
}
