/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class TKfield extends Token
{
    public TKfield()
    {
        super.setText("field");
    }

    public TKfield(int line, int pos)
    {
        super.setText("field");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKfield(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKfield(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKfield text.");
    }
}
