/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class TKinstanceof extends Token
{
    public TKinstanceof()
    {
        super.setText("instanceof");
    }

    public TKinstanceof(int line, int pos)
    {
        super.setText("instanceof");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKinstanceof(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKinstanceof(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKinstanceof text.");
    }
}
