/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class TKis extends Token
{
    public TKis()
    {
        super.setText("is");
    }

    public TKis(int line, int pos)
    {
        super.setText("is");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKis(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKis(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKis text.");
    }
}
