/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class TKoverride extends Token
{
    public TKoverride()
    {
        super.setText("override");
    }

    public TKoverride(int line, int pos)
    {
        super.setText("override");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKoverride(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKoverride(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKoverride text.");
    }
}
