/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class TKthis extends Token
{
    public TKthis()
    {
        super.setText("this");
    }

    public TKthis(int line, int pos)
    {
        super.setText("this");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKthis(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKthis(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKthis text.");
    }
}
