/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.node;

import plume.analysis.*;

@SuppressWarnings("nls")
public final class TL extends Token
{
    public TL()
    {
        super.setText("<");
    }

    public TL(int line, int pos)
    {
        super.setText("<");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TL(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTL(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TL text.");
    }
}
