/* This file was generated by SableCC (http://www.sablecc.org/). */

package plume.parser;

import plume.node.*;
import plume.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 0;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 1;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 2;
    }

    @Override
    public void caseTMul(@SuppressWarnings("unused") TMul node)
    {
        this.index = 3;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 4;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 5;
    }

    @Override
    public void caseTLe(@SuppressWarnings("unused") TLe node)
    {
        this.index = 6;
    }

    @Override
    public void caseTL(@SuppressWarnings("unused") TL node)
    {
        this.index = 7;
    }

    @Override
    public void caseTEq(@SuppressWarnings("unused") TEq node)
    {
        this.index = 8;
    }

    @Override
    public void caseTNeq(@SuppressWarnings("unused") TNeq node)
    {
        this.index = 9;
    }

    @Override
    public void caseTB(@SuppressWarnings("unused") TB node)
    {
        this.index = 10;
    }

    @Override
    public void caseTBe(@SuppressWarnings("unused") TBe node)
    {
        this.index = 11;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 12;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 13;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 14;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 15;
    }

    @Override
    public void caseTSeta(@SuppressWarnings("unused") TSeta node)
    {
        this.index = 16;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 17;
    }

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 18;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 19;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 20;
    }

    @Override
    public void caseTKclass(@SuppressWarnings("unused") TKclass node)
    {
        this.index = 21;
    }

    @Override
    public void caseTKmethod(@SuppressWarnings("unused") TKmethod node)
    {
        this.index = 22;
    }

    @Override
    public void caseTKoverride(@SuppressWarnings("unused") TKoverride node)
    {
        this.index = 23;
    }

    @Override
    public void caseTKextends(@SuppressWarnings("unused") TKextends node)
    {
        this.index = 24;
    }

    @Override
    public void caseTKfield(@SuppressWarnings("unused") TKfield node)
    {
        this.index = 25;
    }

    @Override
    public void caseTKif(@SuppressWarnings("unused") TKif node)
    {
        this.index = 26;
    }

    @Override
    public void caseTKthen(@SuppressWarnings("unused") TKthen node)
    {
        this.index = 27;
    }

    @Override
    public void caseTKelse(@SuppressWarnings("unused") TKelse node)
    {
        this.index = 28;
    }

    @Override
    public void caseTKnew(@SuppressWarnings("unused") TKnew node)
    {
        this.index = 29;
    }

    @Override
    public void caseTKthis(@SuppressWarnings("unused") TKthis node)
    {
        this.index = 30;
    }

    @Override
    public void caseTKsuper(@SuppressWarnings("unused") TKsuper node)
    {
        this.index = 31;
    }

    @Override
    public void caseTKis(@SuppressWarnings("unused") TKis node)
    {
        this.index = 32;
    }

    @Override
    public void caseTKerror(@SuppressWarnings("unused") TKerror node)
    {
        this.index = 33;
    }

    @Override
    public void caseTKabstract(@SuppressWarnings("unused") TKabstract node)
    {
        this.index = 34;
    }

    @Override
    public void caseTKinstanceof(@SuppressWarnings("unused") TKinstanceof node)
    {
        this.index = 35;
    }

    @Override
    public void caseTTrue(@SuppressWarnings("unused") TTrue node)
    {
        this.index = 36;
    }

    @Override
    public void caseTFalse(@SuppressWarnings("unused") TFalse node)
    {
        this.index = 37;
    }

    @Override
    public void caseTKas(@SuppressWarnings("unused") TKas node)
    {
        this.index = 38;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 39;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 40;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 41;
    }
}
